### ISSUE TITLE
Need to release?

### ISSUE THREAD

**Issue by Dotrar** [BDHU/minimalist#1]
I like the theme, and I'm new to Jekyll, but the instructions are not clear. I get error:

```
/home/dre/gems/gems/jekyll-remote-theme-0.4.3/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess': 404 - Not Found - Loading URL: https://codeload.github.com/bdhu/minimalist/zip/v0.1.0 (Jekyll::RemoteTheme::DownloadError)
```

I can use other `remote_themes` just fine. do you need to make a release for this?

**Comment by BDHU** [comment]
The README is not updated yet to reflect the most recent information about this project. To make remote theme possible, we need to convert a customized site into a Ruby gem (which I haven't done yet). A simpler and hacky way is to fork this repo and make modifications based on your needs.

**Comment by BDHU** [comment]
I update the README. It should work fine now. Information regarding how to use Jekyll remote theme can be found [here](https://github.com/benbalter/jekyll-remote-theme).  This [repo](https://github.com/BDHU/bdhu.github.io) uses this theme through remote theme and you can take a look at the `_config.yml` file in that repo to see how. I'm closing this issue now.
