### ISSUE TITLE
Sidebar with long titles

### ISSUE THREAD

**Issue by thetheodor** [BDHU/minimalist#5]
Hi, thanks for making this theme public! 

I'm having the following issue: following the [linked example](https://github.com/BDHU/bdhu.github.io/blob/master/_config.yml) I'm using `title` in `_config.yml` for my first and last names, however, the latter (Theodoridis) is unusually long and the last letter (s) is being cut-off in half when rendering the sidebar. 

Is there an easy way to include some padding?

**Comment by BDHU** [comment]
You can reduce the title's font size by copying the file in the minimalist repo [_sass/jekyll-theme-minimalist.scss](https://github.com/BDHU/minimalist/blob/main/_sass/jekyll-theme-minimalist.scss#L26) to your own working directory (with the exact same directory structure, so you will have the path like \<your repo\>/_sass/jekyll-theme-minimalist.scss) and simply change the `h1`'s font-size.

**Comment by thetheodor** [comment]
Thanks! It worked flawlessly.
