### ISSUE TITLE
Cannot see Python syntax in dark mode

### ISSUE THREAD

**Issue by emiliebarnard** [BDHU/minimalist#8]
When using dark mode, some python key words are difficult to read. 
<img width="637" alt="Screenshot 2023-05-04 at 6 24 52 PM" src="https://user-images.githubusercontent.com/1448658/236360834-d74ab608-aaf4-4ce4-83be-2e2a8e541867.png">
Here, you are unable to see the keyword `in`.

**Comment by lijqhs** [comment]
I have made a pull request to address this small issue.

**Comment by emiliebarnard** [comment]
@lijqhs thank you. Do you know how I can update my code to include your update? For some reason what I did here didn't work: https://github.com/emiliebarnard/pokemon-in-python/blob/gh-pages/_sass/rouge-github.scss

**Comment by emiliebarnard** [comment]
Ah! I changed the remote theme to be `lijqhs/minimalist` instead of `BDHU/minimalist `and now it's working for me. Thank you. :)

Would still recommend this pull request to be approved.

**Comment by lijqhs** [comment]
glad it's helpful
